# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b28ffee197a355a0583b8b7f87d0ce86b3846bd1ab9368a7de7e4eee690c659a27cdecfdb1b6eeea68146390b887f65c551334f41ca09b148137b3a295cd72f2

test:
  secret_key_base: d0d66233a092441c77c41929046f87d79204b7444786134b6d98fd3ff7226cec46403b1c1d92bd957c61849549e83827053b8b60282346a6dbbbcab978526301

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
